version: "3"

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - /db_mongo/data/db