version: "3"

services:
  web:
    build: .
    command: npm run dev
    volumes:
      - ./:/app/
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - /db_mongo:/data/db